// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "AStarSystem.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void registerScriptReflection() {
    {
        Engine::ComponentReflection refl;
        refl.name = "AStarAgent";
        refl.category = "General";
        refl.displayName = "AStarAgent";
        refl.fields = {
            { "targetTransform", Engine::FieldType::Entity, offsetof(AStarAgent, targetTransform) },
            { "speed", Engine::FieldType::Float, offsetof(AStarAgent, speed) },
            { "allowDiagonal", Engine::FieldType::Bool, offsetof(AStarAgent, allowDiagonal) },
            { "showDebugPath", Engine::FieldType::Bool, offsetof(AStarAgent, showDebugPath) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AStarAgent>(e, AStarAgent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AStarAgent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AStarAgent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AStarAgent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
}

static std::vector<std::shared_ptr<System>> s_pluginSystems;

PLUGIN_API void initPlugin(PluginContext* context) {
    if (context && context->imguiContext) ImGui::SetCurrentContext(context->imguiContext);
    registerScriptReflection();

    s_pluginSystems.clear();

    // Register AStarSystem
    {
        auto sysPtr = std::make_shared<AStarSystem>(*context->registry, *context->renderer, *context->editorMode);
        s_pluginSystems.push_back(sysPtr);
        context->systemManager->addSystem(sysPtr);
    }

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    if (context && context->systemManager) {
        for (auto& sysPtr : s_pluginSystems) {
            context->systemManager->removeSystem(sysPtr);
        }
    }
    s_pluginSystems.clear();
}
