// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "ecs/components/PhysgunScript.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void registerScriptReflection() {
    {
        Engine::ComponentReflection refl;
        refl.name = "PhysgunScript";
        refl.category = "General";
        refl.displayName = "Physgun Script";
        refl.fields = {
            { "Kp", Engine::FieldType::Float, offsetof(PhysgunScript, Kp) },
            { "Kd", Engine::FieldType::Float, offsetof(PhysgunScript, Kd) },
            { "holdDistance", Engine::FieldType::Float, offsetof(PhysgunScript, holdDistance) },
            { "isHolding", Engine::FieldType::Bool, offsetof(PhysgunScript, isHolding) },
            { "currentHoldDistance", Engine::FieldType::Float, offsetof(PhysgunScript, currentHoldDistance) },
            { "debugShowRay", Engine::FieldType::Bool, offsetof(PhysgunScript, debugShowRay) },
            { "originEntity", Engine::FieldType::Entity, offsetof(PhysgunScript, originEntity) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<PhysgunScript>(e, PhysgunScript{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<PhysgunScript>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<PhysgunScript>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<PhysgunScript>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
}

static std::vector<std::shared_ptr<System>> s_pluginSystems;

PLUGIN_API void initPlugin(PluginContext* context) {
    if (context && context->imguiContext) ImGui::SetCurrentContext(context->imguiContext);
    registerScriptReflection();

    s_pluginSystems.clear();

    // Register PhysgunSystem
    {
        auto sysPtr = std::make_shared<PhysgunSystem>(*context->registry, *context->renderer, *context->editorMode);
        s_pluginSystems.push_back(sysPtr);
        context->systemManager->addSystem(sysPtr);
    }

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    if (context && context->systemManager) {
        for (auto& sysPtr : s_pluginSystems) {
            context->systemManager->removeSystem(sysPtr);
        }
    }
    s_pluginSystems.clear();
}
