// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "ecs/components/AnimationController.hpp"
#include "ecs/components/Animator.hpp"
#include "ecs/components/AudioListener.hpp"
#include "ecs/components/AudioSource.hpp"
#include "ecs/components/Camera.hpp"
#include "ecs/components/Collider.hpp"
#include "ecs/components/Grid.hpp"
#include "ecs/components/IKSolver.hpp"
#include "ecs/components/inputComponent.hpp"
#include "ecs/components/LightComponent.hpp"
#include "ecs/components/Material.hpp"
#include "ecs/components/PlayerControllerComponent.hpp"
#include "ecs/components/PrefabComponent.hpp"
#include "ecs/components/Renderable.hpp"
#include "ecs/components/RigidBody.hpp"
#include "ecs/components/Skeleton.hpp"
#include "ecs/components/SpriteRenderer.hpp"
#include "ecs/components/Tilemap.hpp"
#include "ecs/components/Transform.hpp"
#include "ecs/components/UIComponents.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void registerEngineReflection() {
    {
        Engine::ComponentReflection refl;
        refl.name = "AnimationController";
        refl.category = "Animation";
        refl.displayName = "Animation Controller";
        refl.fields = {
            { "currentState", Engine::FieldType::String, offsetof(AnimationControllerComponent, currentState) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AnimationControllerComponent>(e, AnimationControllerComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AnimationControllerComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AnimationControllerComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AnimationControllerComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Animator";
        refl.category = "Animation";
        refl.displayName = "Animator";
        refl.fields = {
            { "playbackSpeed", Engine::FieldType::Float, offsetof(AnimatorComponent, playbackSpeed) },
            { "loop", Engine::FieldType::Bool, offsetof(AnimatorComponent, loop) },
            { "isPreviewing", Engine::FieldType::Bool, offsetof(AnimatorComponent, isPreviewing) },
            { "loadedAnimPath", Engine::FieldType::String, offsetof(AnimatorComponent, loadedAnimPath) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AnimatorComponent>(e, AnimatorComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AnimatorComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AnimatorComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AnimatorComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "AudioListener";
        refl.category = "Audio";
        refl.displayName = "Audio Listener";
        refl.fields = {
            { "active", Engine::FieldType::Bool, offsetof(AudioListenerComponent, active) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AudioListenerComponent>(e, AudioListenerComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AudioListenerComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AudioListenerComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AudioListenerComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "AudioSource";
        refl.category = "Audio";
        refl.displayName = "Audio Source";
        refl.fields = {
            { "clipPath", Engine::FieldType::String, offsetof(AudioSourceComponent, clipPath) },
            { "volume", Engine::FieldType::Float, offsetof(AudioSourceComponent, volume) },
            { "pitch", Engine::FieldType::Float, offsetof(AudioSourceComponent, pitch) },
            { "loop", Engine::FieldType::Bool, offsetof(AudioSourceComponent, loop) },
            { "playOnAwake", Engine::FieldType::Bool, offsetof(AudioSourceComponent, playOnAwake) },
            { "spatialized", Engine::FieldType::Bool, offsetof(AudioSourceComponent, spatialized) },
            { "minDistance", Engine::FieldType::Float, offsetof(AudioSourceComponent, minDistance) },
            { "maxDistance", Engine::FieldType::Float, offsetof(AudioSourceComponent, maxDistance) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AudioSourceComponent>(e, AudioSourceComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AudioSourceComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AudioSourceComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AudioSourceComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Camera";
        refl.category = "Rendering & Lights";
        refl.displayName = "Camera";
        refl.fields = {
            { "isOrthographic", Engine::FieldType::Bool, offsetof(Camera, isOrthographic) },
            { "orthoSize", Engine::FieldType::Float, offsetof(Camera, orthoSize) },
            { "fov", Engine::FieldType::Float, offsetof(Camera, fov) },
            { "aspect", Engine::FieldType::Float, offsetof(Camera, aspect) },
            { "nearPlane", Engine::FieldType::Float, offsetof(Camera, nearPlane) },
            { "farPlane", Engine::FieldType::Float, offsetof(Camera, farPlane) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Camera>(e, Camera{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Camera>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Camera>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Camera>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Collider";
        refl.category = "Physics";
        refl.displayName = "Collider";
        refl.fields = {
            { "radius", Engine::FieldType::Float, offsetof(ColliderComponent, radius) },
            { "height", Engine::FieldType::Float, offsetof(ColliderComponent, height) },
            { "extents", Engine::FieldType::Vec3, offsetof(ColliderComponent, extents) },
            { "offset", Engine::FieldType::Vec3, offsetof(ColliderComponent, offset) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<ColliderComponent>(e, ColliderComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<ColliderComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<ColliderComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<ColliderComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Grid";
        refl.category = "Rendering & Lights";
        refl.displayName = "Grid";
        refl.fields = {
            { "colorID", Engine::FieldType::Int, offsetof(Grid, colorID) },
            { "meshID", Engine::FieldType::Int, offsetof(Grid, meshID) },
            { "spacing", Engine::FieldType::Float, offsetof(Grid, spacing) },
            { "size", Engine::FieldType::Float, offsetof(Grid, size) },
            { "color", Engine::FieldType::Vec4, offsetof(Grid, color) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Grid>(e, Grid{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Grid>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Grid>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Grid>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "IKSolver";
        refl.category = "Animation";
        refl.displayName = "IK Solver";
        refl.fields = {
            { "startJointName", Engine::FieldType::String, offsetof(IKSolverComponent, startJointName) },
            { "middleJointName", Engine::FieldType::String, offsetof(IKSolverComponent, middleJointName) },
            { "endJointName", Engine::FieldType::String, offsetof(IKSolverComponent, endJointName) },
            { "maxIterations", Engine::FieldType::Int, offsetof(IKSolverComponent, maxIterations) },
            { "tolerance", Engine::FieldType::Float, offsetof(IKSolverComponent, tolerance) },
            { "targetPosition", Engine::FieldType::Vec3, offsetof(IKSolverComponent, targetPosition) },
            { "polePosition", Engine::FieldType::Vec3, offsetof(IKSolverComponent, polePosition) },
            { "targetWeight", Engine::FieldType::Float, offsetof(IKSolverComponent, targetWeight) },
            { "enabled", Engine::FieldType::Bool, offsetof(IKSolverComponent, enabled) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<IKSolverComponent>(e, IKSolverComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<IKSolverComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<IKSolverComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<IKSolverComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Input";
        refl.category = "Gameplay";
        refl.displayName = "Input";
        refl.fields = {
            { "movement", Engine::FieldType::Vec3, offsetof(InputComponent, movement) },
            { "look", Engine::FieldType::Vec2, offsetof(InputComponent, look) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<InputComponent>(e, InputComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<InputComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<InputComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<InputComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Light";
        refl.category = "Rendering & Lights";
        refl.displayName = "Light";
        refl.fields = {
            { "color", Engine::FieldType::Vec3, offsetof(Engine::LightComponent, color) },
            { "intensity", Engine::FieldType::Float, offsetof(Engine::LightComponent, intensity) },
            { "range", Engine::FieldType::Float, offsetof(Engine::LightComponent, range) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::LightComponent>(e, Engine::LightComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::LightComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::LightComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::LightComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Material";
        refl.category = "Rendering & Lights";
        refl.displayName = "Material";
        refl.fields = {
            { "color", Engine::FieldType::Vec4, offsetof(Material, color) },
            { "texturePath", Engine::FieldType::String, offsetof(Material, texturePath) },
            { "shaderName", Engine::FieldType::String, offsetof(Material, shaderName) },
            { "normalMapPath", Engine::FieldType::String, offsetof(Material, normalMapPath) },
            { "metallicMapPath", Engine::FieldType::String, offsetof(Material, metallicMapPath) },
            { "roughness", Engine::FieldType::Float, offsetof(Material, roughness) },
            { "metallic", Engine::FieldType::Float, offsetof(Material, metallic) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Material>(e, Material{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Material>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Material>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Material>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "PlayerController";
        refl.category = "Gameplay";
        refl.displayName = "Player Controller";
        refl.fields = {
            { "speed", Engine::FieldType::Float, offsetof(PlayerControllerComponent, speed) },
            { "jumpForce", Engine::FieldType::Float, offsetof(PlayerControllerComponent, jumpForce) },
            { "interactRange", Engine::FieldType::Float, offsetof(PlayerControllerComponent, interactRange) },
            { "orientToMovement", Engine::FieldType::Bool, offsetof(PlayerControllerComponent, orientToMovement) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<PlayerControllerComponent>(e, PlayerControllerComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<PlayerControllerComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<PlayerControllerComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<PlayerControllerComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Prefab";
        refl.category = "General";
        refl.displayName = "Prefab";
        refl.fields = {
            { "prefabAssetPath", Engine::FieldType::String, offsetof(Engine::PrefabComponent, prefabAssetPath) },
            { "isRootInstance", Engine::FieldType::Bool, offsetof(Engine::PrefabComponent, isRootInstance) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::PrefabComponent>(e, Engine::PrefabComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::PrefabComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::PrefabComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::PrefabComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Renderable";
        refl.category = "Rendering & Lights";
        refl.displayName = "Renderable";
        refl.fields = {
            { "meshID", Engine::FieldType::Int, offsetof(Renderable, meshID) },
            { "materialID", Engine::FieldType::Int, offsetof(Renderable, materialID) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Renderable>(e, Renderable{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Renderable>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Renderable>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Renderable>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "RigidBody";
        refl.category = "Physics";
        refl.displayName = "Rigid Body";
        refl.fields = {
            { "mass", Engine::FieldType::Float, offsetof(RigidBodyComponent, mass) },
            { "velocity", Engine::FieldType::Vec3, offsetof(RigidBodyComponent, velocity) },
            { "acceleration", Engine::FieldType::Vec3, offsetof(RigidBodyComponent, acceleration) },
            { "force", Engine::FieldType::Vec3, offsetof(RigidBodyComponent, force) },
            { "gravityScale", Engine::FieldType::Float, offsetof(RigidBodyComponent, gravityScale) },
            { "restitution", Engine::FieldType::Float, offsetof(RigidBodyComponent, restitution) },
            { "friction", Engine::FieldType::Float, offsetof(RigidBodyComponent, friction) },
            { "angularVelocity", Engine::FieldType::Vec3, offsetof(RigidBodyComponent, angularVelocity) },
            { "torque", Engine::FieldType::Vec3, offsetof(RigidBodyComponent, torque) },
            { "angularDrag", Engine::FieldType::Float, offsetof(RigidBodyComponent, angularDrag) },
            { "linearDrag", Engine::FieldType::Float, offsetof(RigidBodyComponent, linearDrag) },
            { "freezePositionX", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezePositionX) },
            { "freezePositionY", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezePositionY) },
            { "freezePositionZ", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezePositionZ) },
            { "freezeRotationX", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezeRotationX) },
            { "freezeRotationY", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezeRotationY) },
            { "freezeRotationZ", Engine::FieldType::Bool, offsetof(RigidBodyComponent, freezeRotationZ) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<RigidBodyComponent>(e, RigidBodyComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<RigidBodyComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<RigidBodyComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<RigidBodyComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Skeleton";
        refl.category = "Animation";
        refl.displayName = "Skeleton";
        refl.fields = {
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<SkeletonComponent>(e, SkeletonComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<SkeletonComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<SkeletonComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<SkeletonComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "SpriteRenderer";
        refl.category = "Rendering & Lights";
        refl.displayName = "Sprite Renderer";
        refl.fields = {
            { "texturePath", Engine::FieldType::String, offsetof(Engine::SpriteRenderer, texturePath) },
            { "color", Engine::FieldType::Vec4, offsetof(Engine::SpriteRenderer, color) },
            { "flipX", Engine::FieldType::Bool, offsetof(Engine::SpriteRenderer, flipX) },
            { "flipY", Engine::FieldType::Bool, offsetof(Engine::SpriteRenderer, flipY) },
            { "sortOrder", Engine::FieldType::Int, offsetof(Engine::SpriteRenderer, sortOrder) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::SpriteRenderer>(e, Engine::SpriteRenderer{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::SpriteRenderer>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::SpriteRenderer>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::SpriteRenderer>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Tilemap";
        refl.category = "Rendering & Lights";
        refl.displayName = "Tilemap";
        refl.fields = {
            { "width", Engine::FieldType::Int, offsetof(Engine::TilemapComponent, width) },
            { "height", Engine::FieldType::Int, offsetof(Engine::TilemapComponent, height) },
            { "tileSize", Engine::FieldType::Float, offsetof(Engine::TilemapComponent, tileSize) },
            { "tilesetPath", Engine::FieldType::String, offsetof(Engine::TilemapComponent, tilesetPath) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::TilemapComponent>(e, Engine::TilemapComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::TilemapComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::TilemapComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::TilemapComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Transform";
        refl.category = "General";
        refl.displayName = "Transform";
        refl.fields = {
            { "position", Engine::FieldType::Vec3, offsetof(Transform, position) },
            { "rotation", Engine::FieldType::Vec3, offsetof(Transform, rotation) },
            { "scale", Engine::FieldType::Vec3, offsetof(Transform, scale) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Transform>(e, Transform{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Transform>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Transform>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Transform>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Canvas";
        refl.category = "UI";
        refl.displayName = "Canvas";
        refl.fields = {
            { "isScreenSpace", Engine::FieldType::Bool, offsetof(Engine::CanvasComponent, isScreenSpace) },
            { "isVisible", Engine::FieldType::Bool, offsetof(Engine::CanvasComponent, isVisible) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::CanvasComponent>(e, Engine::CanvasComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::CanvasComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::CanvasComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::CanvasComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "RectTransform";
        refl.category = "UI";
        refl.displayName = "Rect Transform";
        refl.fields = {
            { "anchorMin", Engine::FieldType::Vec2, offsetof(Engine::RectTransform, anchorMin) },
            { "anchorMax", Engine::FieldType::Vec2, offsetof(Engine::RectTransform, anchorMax) },
            { "anchoredPosition", Engine::FieldType::Vec2, offsetof(Engine::RectTransform, anchoredPosition) },
            { "sizeDelta", Engine::FieldType::Vec2, offsetof(Engine::RectTransform, sizeDelta) },
            { "pivot", Engine::FieldType::Vec2, offsetof(Engine::RectTransform, pivot) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::RectTransform>(e, Engine::RectTransform{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::RectTransform>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::RectTransform>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::RectTransform>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIPanel";
        refl.category = "UI";
        refl.displayName = "UI Panel";
        refl.fields = {
            { "color", Engine::FieldType::Vec4, offsetof(Engine::UIPanelComponent, color) },
            { "borderRadius", Engine::FieldType::Float, offsetof(Engine::UIPanelComponent, borderRadius) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIPanelComponent>(e, Engine::UIPanelComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIPanelComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIPanelComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIPanelComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIImage";
        refl.category = "UI";
        refl.displayName = "UI Image";
        refl.fields = {
            { "texturePath", Engine::FieldType::String, offsetof(Engine::UIImageComponent, texturePath) },
            { "tintColor", Engine::FieldType::Vec4, offsetof(Engine::UIImageComponent, tintColor) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIImageComponent>(e, Engine::UIImageComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIImageComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIImageComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIImageComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIText";
        refl.category = "UI";
        refl.displayName = "UI Text";
        refl.fields = {
            { "text", Engine::FieldType::String, offsetof(Engine::UITextComponent, text) },
            { "color", Engine::FieldType::Vec4, offsetof(Engine::UITextComponent, color) },
            { "fontSize", Engine::FieldType::Float, offsetof(Engine::UITextComponent, fontSize) },
            { "alignCenter", Engine::FieldType::Bool, offsetof(Engine::UITextComponent, alignCenter) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UITextComponent>(e, Engine::UITextComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UITextComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UITextComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UITextComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIButton";
        refl.category = "UI";
        refl.displayName = "UI Button";
        refl.fields = {
            { "label", Engine::FieldType::String, offsetof(Engine::UIButtonComponent, label) },
            { "normalColor", Engine::FieldType::Vec4, offsetof(Engine::UIButtonComponent, normalColor) },
            { "hoverColor", Engine::FieldType::Vec4, offsetof(Engine::UIButtonComponent, hoverColor) },
            { "pressedColor", Engine::FieldType::Vec4, offsetof(Engine::UIButtonComponent, pressedColor) },
            { "textColor", Engine::FieldType::Vec4, offsetof(Engine::UIButtonComponent, textColor) },
            { "clickEventName", Engine::FieldType::String, offsetof(Engine::UIButtonComponent, clickEventName) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIButtonComponent>(e, Engine::UIButtonComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIButtonComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIButtonComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIButtonComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIGridLayoutGroup";
        refl.category = "UI";
        refl.displayName = "UI Grid Layout Group";
        refl.fields = {
            { "cellSize", Engine::FieldType::Vec2, offsetof(Engine::UIGridLayoutGroupComponent, cellSize) },
            { "spacing", Engine::FieldType::Vec2, offsetof(Engine::UIGridLayoutGroupComponent, spacing) },
            { "padding", Engine::FieldType::Vec4, offsetof(Engine::UIGridLayoutGroupComponent, padding) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIGridLayoutGroupComponent>(e, Engine::UIGridLayoutGroupComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIGridLayoutGroupComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIGridLayoutGroupComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIGridLayoutGroupComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UILayoutGroup";
        refl.category = "UI";
        refl.displayName = "UI Layout Group";
        refl.fields = {
            { "isVertical", Engine::FieldType::Bool, offsetof(Engine::UILayoutGroupComponent, isVertical) },
            { "spacing", Engine::FieldType::Float, offsetof(Engine::UILayoutGroupComponent, spacing) },
            { "padding", Engine::FieldType::Vec4, offsetof(Engine::UILayoutGroupComponent, padding) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UILayoutGroupComponent>(e, Engine::UILayoutGroupComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UILayoutGroupComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UILayoutGroupComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UILayoutGroupComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIScrollRect";
        refl.category = "UI";
        refl.displayName = "UI Scroll Rect";
        refl.fields = {
            { "horizontal", Engine::FieldType::Bool, offsetof(Engine::UIScrollRectComponent, horizontal) },
            { "vertical", Engine::FieldType::Bool, offsetof(Engine::UIScrollRectComponent, vertical) },
            { "scrollPosition", Engine::FieldType::Vec2, offsetof(Engine::UIScrollRectComponent, scrollPosition) },
            { "scrollSpeed", Engine::FieldType::Float, offsetof(Engine::UIScrollRectComponent, scrollSpeed) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIScrollRectComponent>(e, Engine::UIScrollRectComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIScrollRectComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIScrollRectComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIScrollRectComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UISlider";
        refl.category = "UI";
        refl.displayName = "UI Slider";
        refl.fields = {
            { "value", Engine::FieldType::Float, offsetof(Engine::UISliderComponent, value) },
            { "minValue", Engine::FieldType::Float, offsetof(Engine::UISliderComponent, minValue) },
            { "maxValue", Engine::FieldType::Float, offsetof(Engine::UISliderComponent, maxValue) },
            { "backgroundColor", Engine::FieldType::Vec4, offsetof(Engine::UISliderComponent, backgroundColor) },
            { "fillColor", Engine::FieldType::Vec4, offsetof(Engine::UISliderComponent, fillColor) },
            { "handleColor", Engine::FieldType::Vec4, offsetof(Engine::UISliderComponent, handleColor) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UISliderComponent>(e, Engine::UISliderComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UISliderComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UISliderComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UISliderComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "UIToggle";
        refl.category = "UI";
        refl.displayName = "UI Toggle";
        refl.fields = {
            { "isOn", Engine::FieldType::Bool, offsetof(Engine::UIToggleComponent, isOn) },
            { "label", Engine::FieldType::String, offsetof(Engine::UIToggleComponent, label) },
            { "boxColor", Engine::FieldType::Vec4, offsetof(Engine::UIToggleComponent, boxColor) },
            { "checkmarkColor", Engine::FieldType::Vec4, offsetof(Engine::UIToggleComponent, checkmarkColor) },
            { "textColor", Engine::FieldType::Vec4, offsetof(Engine::UIToggleComponent, textColor) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<Engine::UIToggleComponent>(e, Engine::UIToggleComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<Engine::UIToggleComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<Engine::UIToggleComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<Engine::UIToggleComponent>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
}

static std::vector<std::shared_ptr<System>> s_pluginSystems;

PLUGIN_API void initPlugin(PluginContext* context) {
    if (context && context->imguiContext) ImGui::SetCurrentContext(context->imguiContext);
    registerEngineReflection();

    s_pluginSystems.clear();

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    if (context && context->systemManager) {
        for (auto& sysPtr : s_pluginSystems) {
            context->systemManager->removeSystem(sysPtr);
        }
    }
    s_pluginSystems.clear();
}
