// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "CinemachineComponent.hpp"
#include "CinemachineSystem.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void registerScriptReflection() {
    {
        Engine::ComponentReflection refl;
        refl.name = "CinemachineVirtualCamera";
        refl.category = "General";
        refl.displayName = "CinemachineVirtualCamera";
        refl.fields = {
            { "followTargetName", Engine::FieldType::String, offsetof(CinemachineVirtualCamera, followTargetName) },
            { "lookAtTargetName", Engine::FieldType::String, offsetof(CinemachineVirtualCamera, lookAtTargetName) },
            { "lockToBone", Engine::FieldType::String, offsetof(CinemachineVirtualCamera, lockToBone) },
            { "mode", Engine::FieldType::Enum, offsetof(CinemachineVirtualCamera, mode), { "Third Person Follow", "First Person", "Fixed Look At", "2D Follow" } },
            { "mouseOrbit", Engine::FieldType::Bool, offsetof(CinemachineVirtualCamera, mouseOrbit) },
            { "mouseLook", Engine::FieldType::Bool, offsetof(CinemachineVirtualCamera, mouseLook) },
            { "orbitSensitivity", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, orbitSensitivity) },
            { "orbitYaw", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, orbitYaw) },
            { "orbitPitch", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, orbitPitch) },
            { "cameraYaw", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, cameraYaw) },
            { "cameraPitch", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, cameraPitch) },
            { "followOffset", Engine::FieldType::Vec3, offsetof(CinemachineVirtualCamera, followOffset) },
            { "followDamping", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, followDamping) },
            { "lookAtDamping", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, lookAtDamping) },
            { "fov", Engine::FieldType::Float, offsetof(CinemachineVirtualCamera, fov) },
            { "priority", Engine::FieldType::Int, offsetof(CinemachineVirtualCamera, priority) },
            { "active", Engine::FieldType::Bool, offsetof(CinemachineVirtualCamera, active) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<CinemachineVirtualCamera>(e, CinemachineVirtualCamera{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<CinemachineVirtualCamera>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<CinemachineVirtualCamera>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<CinemachineVirtualCamera>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
}

static std::vector<std::shared_ptr<System>> s_pluginSystems;

PLUGIN_API void initPlugin(PluginContext* context) {
    if (context && context->imguiContext) ImGui::SetCurrentContext(context->imguiContext);
    registerScriptReflection();

    s_pluginSystems.clear();

    // Register CinemachineSystem
    {
        auto sysPtr = std::make_shared<CinemachineSystem>(*context->registry, *context->renderer, *context->editorMode);
        s_pluginSystems.push_back(sysPtr);
        context->systemManager->addSystem(sysPtr);
    }

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    if (context && context->systemManager) {
        for (auto& sysPtr : s_pluginSystems) {
            context->systemManager->removeSystem(sysPtr);
        }
    }
    s_pluginSystems.clear();
}
