// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "AtmosphereComponent.hpp"
#include "VolumetricCloudComponent.hpp"
#include "VolumetricFogComponent.hpp"
#include "WeatherComponent.hpp"
#include "AtmosphereSystem.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void registerScriptReflection() {
    {
        Engine::ComponentReflection refl;
        refl.name = "Atmosphere";
        refl.category = "Atmosphere";
        refl.displayName = "Atmosphere Component";
        refl.fields = {
            { "bottomRadius", Engine::FieldType::Float, offsetof(AtmosphereComponent, bottomRadius) },
            { "topRadius", Engine::FieldType::Float, offsetof(AtmosphereComponent, topRadius) },
            { "rayleighScattering", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, rayleighScattering) },
            { "rayleighAbsorption", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, rayleighAbsorption) },
            { "mieScattering", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, mieScattering) },
            { "mieAbsorption", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, mieAbsorption) },
            { "absorptionExtinction", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, absorptionExtinction) },
            { "rayleighDensity", Engine::FieldType::Struct, offsetof(AtmosphereComponent, rayleighDensity), {}, {
                { "layers[0]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[0]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" },
                { "layers[1]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[1]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" }
            }, "AtmosphereDensityProfile" },
            { "mieDensity", Engine::FieldType::Struct, offsetof(AtmosphereComponent, mieDensity), {}, {
                { "layers[0]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[0]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" },
                { "layers[1]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[1]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" }
            }, "AtmosphereDensityProfile" },
            { "absorptionDensity", Engine::FieldType::Struct, offsetof(AtmosphereComponent, absorptionDensity), {}, {
                { "layers[0]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[0]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" },
                { "layers[1]", Engine::FieldType::Struct, offsetof(AtmosphereDensityProfile, layers[1]), {}, {
                    { "width", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, width) },
                    { "expTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expTerm) },
                    { "expScale", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, expScale) },
                    { "linearTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, linearTerm) },
                    { "constantTerm", Engine::FieldType::Float, offsetof(AtmosphereDensityLayer, constantTerm) }
                }, "AtmosphereDensityLayer" }
            }, "AtmosphereDensityProfile" },
            { "groundAlbedo", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, groundAlbedo) },
            { "solarIrradiance", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, solarIrradiance) },
            { "sunAngularRadius", Engine::FieldType::Float, offsetof(AtmosphereComponent, sunAngularRadius) },
            { "mieAnisotropy", Engine::FieldType::Float, offsetof(AtmosphereComponent, mieAnisotropy) },
            { "enableScattering", Engine::FieldType::Bool, offsetof(AtmosphereComponent, enableScattering) },
            { "enableOzone", Engine::FieldType::Bool, offsetof(AtmosphereComponent, enableOzone) },
            { "enableStars", Engine::FieldType::Bool, offsetof(AtmosphereComponent, enableStars) },
            { "starIntensity", Engine::FieldType::Float, offsetof(AtmosphereComponent, starIntensity) },
            { "starTwinkleSpeed", Engine::FieldType::Float, offsetof(AtmosphereComponent, starTwinkleSpeed) },
            { "enableMoon", Engine::FieldType::Bool, offsetof(AtmosphereComponent, enableMoon) },
            { "moonAngularRadius", Engine::FieldType::Float, offsetof(AtmosphereComponent, moonAngularRadius) },
            { "moonIntensity", Engine::FieldType::Float, offsetof(AtmosphereComponent, moonIntensity) },
            { "moonPhase", Engine::FieldType::Float, offsetof(AtmosphereComponent, moonPhase) },
            { "moonDirection", Engine::FieldType::Vec3, offsetof(AtmosphereComponent, moonDirection) },
            { "autoMoonDirection", Engine::FieldType::Bool, offsetof(AtmosphereComponent, autoMoonDirection) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<AtmosphereComponent>(e, AtmosphereComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<AtmosphereComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<AtmosphereComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<AtmosphereComponent>(e)); };
        refl.isEnabled = [](const Registry& reg, Entity e) { return reg.isComponentEnabled<AtmosphereComponent>(e); };
        refl.setEnabled = [](Registry& reg, Entity e, bool enabled) { reg.setComponentEnabled<AtmosphereComponent>(e, enabled); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "VolumetricCloud";
        refl.category = "Environment";
        refl.displayName = "Volumetric Clouds";
        refl.fields = {
            { "preset", Engine::FieldType::Enum, offsetof(VolumetricCloudComponent, preset), { "Custom", "Clear Sky", "Fair Weather Cumulus", "Scattered Clouds", "Broken Sky", "Overcast", "Stormy" } },
            { "enabled", Engine::FieldType::Bool, offsetof(VolumetricCloudComponent, enabled) },
            { "bottomAltitude", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, bottomAltitude) },
            { "topAltitude", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, topAltitude) },
            { "coverage", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, coverage) },
            { "density", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, density) },
            { "cloudScale", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, cloudScale) },
            { "detailScale", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, detailScale) },
            { "detailErosion", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, detailErosion) },
            { "windDirection", Engine::FieldType::Vec2, offsetof(VolumetricCloudComponent, windDirection) },
            { "windSpeed", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, windSpeed) },
            { "silverLining", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, silverLining) },
            { "powderEffect", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, powderEffect) },
            { "cloudColor", Engine::FieldType::Vec3, offsetof(VolumetricCloudComponent, cloudColor) },
            { "ambientColor", Engine::FieldType::Vec3, offsetof(VolumetricCloudComponent, ambientColor) },
            { "marchSteps", Engine::FieldType::Int, offsetof(VolumetricCloudComponent, marchSteps) },
            { "castShadows", Engine::FieldType::Bool, offsetof(VolumetricCloudComponent, castShadows) },
            { "shadowIntensity", Engine::FieldType::Float, offsetof(VolumetricCloudComponent, shadowIntensity) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<VolumetricCloudComponent>(e, VolumetricCloudComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<VolumetricCloudComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<VolumetricCloudComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<VolumetricCloudComponent>(e)); };
        refl.isEnabled = [](const Registry& reg, Entity e) { return reg.isComponentEnabled<VolumetricCloudComponent>(e); };
        refl.setEnabled = [](Registry& reg, Entity e, bool enabled) { reg.setComponentEnabled<VolumetricCloudComponent>(e, enabled); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "VolumetricFog";
        refl.category = "Environment";
        refl.displayName = "Volumetric Fog";
        refl.fields = {
            { "enabled", Engine::FieldType::Bool, offsetof(VolumetricFogComponent, enabled) },
            { "mode", Engine::FieldType::Enum, offsetof(VolumetricFogComponent, mode), { "Atmospheric Haze", "Dense / Stylized Fog" } },
            { "affectSky", Engine::FieldType::Bool, offsetof(VolumetricFogComponent, affectSky) },
            { "isGlobal", Engine::FieldType::Bool, offsetof(VolumetricFogComponent, isGlobal) },
            { "maxDistance", Engine::FieldType::Float, offsetof(VolumetricFogComponent, maxDistance) },
            { "volumetricFogDistance", Engine::FieldType::Float, offsetof(VolumetricFogComponent, volumetricFogDistance) },
            { "startDistance", Engine::FieldType::Float, offsetof(VolumetricFogComponent, startDistance) },
            { "densityMultiplier", Engine::FieldType::Float, offsetof(VolumetricFogComponent, densityMultiplier) },
            { "fogColorTint", Engine::FieldType::Vec3, offsetof(VolumetricFogComponent, fogColorTint) },
            { "anisotropy", Engine::FieldType::Float, offsetof(VolumetricFogComponent, anisotropy) },
            { "baseHeight", Engine::FieldType::Float, offsetof(VolumetricFogComponent, baseHeight) },
            { "heightFalloff", Engine::FieldType::Float, offsetof(VolumetricFogComponent, heightFalloff) },
            { "groundSunAttenuation", Engine::FieldType::Float, offsetof(VolumetricFogComponent, groundSunAttenuation) },
            { "castShadows", Engine::FieldType::Bool, offsetof(VolumetricFogComponent, castShadows) },
            { "shadowIntensity", Engine::FieldType::Float, offsetof(VolumetricFogComponent, shadowIntensity) },
            { "marchSteps", Engine::FieldType::Int, offsetof(VolumetricFogComponent, marchSteps) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<VolumetricFogComponent>(e, VolumetricFogComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<VolumetricFogComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<VolumetricFogComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<VolumetricFogComponent>(e)); };
        refl.isEnabled = [](const Registry& reg, Entity e) { return reg.isComponentEnabled<VolumetricFogComponent>(e); };
        refl.setEnabled = [](Registry& reg, Entity e, bool enabled) { reg.setComponentEnabled<VolumetricFogComponent>(e, enabled); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
    {
        Engine::ComponentReflection refl;
        refl.name = "Weather";
        refl.category = "Environment";
        refl.displayName = "Weather";
        refl.fields = {
            { "type", Engine::FieldType::Enum, offsetof(WeatherComponent, type), { "Clear", "Rain", "Snow", "Storm" } },
            { "precipitationIntensity", Engine::FieldType::Float, offsetof(WeatherComponent, precipitationIntensity) },
            { "wetness", Engine::FieldType::Float, offsetof(WeatherComponent, wetness) },
            { "autoWetness", Engine::FieldType::Bool, offsetof(WeatherComponent, autoWetness) },
            { "dryingSpeed", Engine::FieldType::Float, offsetof(WeatherComponent, dryingSpeed) },
            { "wetnessAccumSpeed", Engine::FieldType::Float, offsetof(WeatherComponent, wetnessAccumSpeed) },
            { "windDirection", Engine::FieldType::Vec2, offsetof(WeatherComponent, windDirection) },
            { "windSpeed", Engine::FieldType::Float, offsetof(WeatherComponent, windSpeed) },
            { "enableLightning", Engine::FieldType::Bool, offsetof(WeatherComponent, enableLightning) },
            { "lightningFrequency", Engine::FieldType::Float, offsetof(WeatherComponent, lightningFrequency) },
            { "lightningIntensity", Engine::FieldType::Float, offsetof(WeatherComponent, lightningIntensity) },
            { "enableAudio", Engine::FieldType::Bool, offsetof(WeatherComponent, enableAudio) },
            { "rainVolume", Engine::FieldType::Float, offsetof(WeatherComponent, rainVolume) },
            { "thunderVolume", Engine::FieldType::Float, offsetof(WeatherComponent, thunderVolume) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<WeatherComponent>(e, WeatherComponent{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<WeatherComponent>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<WeatherComponent>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<WeatherComponent>(e)); };
        refl.isEnabled = [](const Registry& reg, Entity e) { return reg.isComponentEnabled<WeatherComponent>(e); };
        refl.setEnabled = [](Registry& reg, Entity e, bool enabled) { reg.setComponentEnabled<WeatherComponent>(e, enabled); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }
}

static std::vector<std::shared_ptr<System>> s_pluginSystems;

PLUGIN_API void initPlugin(PluginContext* context) {
    if (context && context->imguiContext) ImGui::SetCurrentContext(context->imguiContext);
    registerScriptReflection();

    s_pluginSystems.clear();

    // Register AtmosphereSystem
    {
        auto sysPtr = std::make_shared<AtmosphereSystem>(*context->registry, *context->renderer, *context->editorMode);
        s_pluginSystems.push_back(sysPtr);
        context->systemManager->addSystem(sysPtr);
    }

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    if (context && context->systemManager) {
        for (auto& sysPtr : s_pluginSystems) {
            context->systemManager->removeSystem(sysPtr);
        }
    }
    s_pluginSystems.clear();
}
